package visao;

import dao.FerramentaDAO;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import modelo.Ferramenta;

/**
 *
 * @author kauem
 */
public class CadastroFerramenta extends javax.swing.JFrame {

    private Ferramenta objetoFerramenta;
    /**
     * Creates new form CadastroFerramenta
     */
    MaskFormatter mfCusto;

    public CadastroFerramenta() {

        try {
            mfCusto = new MaskFormatter("R$##,##");
        } catch (ParseException ex) {
            System.out.println("erro na criação da mascara");
        }

        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroFerramenta.getModel();
        jTableCadastroFerramenta.setRowSorter(new TableRowSorter(modelo));

        // Permitir seleção de múltiplas linhas
        jTableCadastroFerramenta.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        //pra centraliazr a exibição dos valores na tabela
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        // Aplicar o renderer às colunas desejadas (ID e Quantidade)
        jTableCadastroFerramenta.getColumnModel().getColumn(0).setCellRenderer(centerRenderer); // Coluna ID

        readJtable();
    }

    //Método que atualiza a tabela com os valores adicionados
    public void readJtable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroFerramenta.getModel();
        modelo.setNumRows(0);

        FerramentaDAO fdao = new FerramentaDAO();

        for (Ferramenta f : fdao.read()) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getMarca(),
                // f.getCusto(),
                String.format("R$ %.2f", f.getCusto()),});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInserirMarca = new javax.swing.JTextField();
        lblFerramenta = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        txtInserirMarcaa = new javax.swing.JTextField();
        btnCadastrarFerramenta = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroFerramenta = new javax.swing.JTable();
        txtFormatCusto = new javax.swing.JFormattedTextField(mfCusto);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInserirNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        lblUnidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnidade.setText("Custo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Custo");

        txtInserirMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirMarcaActionPerformed(evt);
            }
        });
        txtInserirMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirMarcaKeyPressed(evt);
            }
        });

        lblFerramenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFerramenta.setText("Ferramenta:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar ferramentas");
        setBackground(new java.awt.Color(239, 35, 60));

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarca.setText("Marca");

        txtInserirMarcaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirMarcaaActionPerformed(evt);
            }
        });
        txtInserirMarcaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirMarcaaKeyPressed(evt);
            }
        });

        btnCadastrarFerramenta.setBackground(new java.awt.Color(64, 61, 57));
        btnCadastrarFerramenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCadastrarFerramenta.setForeground(new java.awt.Color(22, 219, 101));
        btnCadastrarFerramenta.setText("Cadastrar");
        btnCadastrarFerramenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnCadastrarFerramenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCadastrarFerramentaFocusGained(evt);
            }
        });
        btnCadastrarFerramenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarFerramentaMouseClicked(evt);
            }
        });
        btnCadastrarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFerramentaActionPerformed(evt);
            }
        });
        btnCadastrarFerramenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCadastrarFerramentaKeyPressed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(64, 61, 57));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(195, 47, 39));
        btnExcluir.setText("Cancelar");
        btnExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jTableCadastroFerramenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Ferramenta", "Marca", "Valor"
            }
        ));
        jTableCadastroFerramenta.setShowHorizontalLines(true);
        jTableCadastroFerramenta.setShowVerticalLines(true);
        jTableCadastroFerramenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadastroFerramentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadastroFerramenta);
        if (jTableCadastroFerramenta.getColumnModel().getColumnCount() > 0) {
            jTableCadastroFerramenta.getColumnModel().getColumn(0).setMaxWidth(55);
        }

        txtFormatCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtFormatCusto.setValue(0.00);
        txtFormatCusto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFormatCustoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFormatCustoFocusLost(evt);
            }
        });
        txtFormatCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFormatCustoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText(" ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nome");

        txtInserirNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirNomeActionPerformed(evt);
            }
        });
        txtInserirNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirNomeKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Custo");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Cadastrar Ferramentas");

        jButton1.setBackground(new java.awt.Color(195, 47, 39));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtInserirNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(txtInserirMarcaa, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFormatCusto, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(1, 1, 1)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInserirMarcaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFormatCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* dados() => mesmo método do botão adicionar, mas usado pra executar
        a ação do botão ao pressionar enter
     */
    private void dados() {

        Ferramenta f = new Ferramenta(); //instancia produto
        FerramentaDAO dao = new FerramentaDAO(); //conecta sql

        //atualiza os valores
        f.setNome(txtInserirNome.getText());
        f.setMarca(txtInserirMarcaa.getText());
        f.setCusto(Double.parseDouble(txtFormatCusto.getText().replace(',', '.')));

        //insere novo objeto dentro da tabela
        dao.create(f);

        //limpando os campos
        txtInserirNome.setText("");
        txtInserirMarcaa.setText("");
        txtFormatCusto.setText("");

        //atualizando tabela
        readJtable();
    }

    private void txtInserirMarcaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirMarcaaActionPerformed
        //label do botão ferramenta
    }//GEN-LAST:event_txtInserirMarcaaActionPerformed

    // BOTAO ADICIONAR
    private void btnCadastrarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFerramentaActionPerformed
        String nome = "";
        String marca = "";
        double preco = 0.0;
        String textoPreco = "";

        try {
            if (this.txtInserirNome.getText().length() <= 2) {
                JOptionPane.showMessageDialog(null, "O campo Nome deve ter no mínimo 3 caracteres.");
            } else {
                nome = this.txtInserirNome.getText();
            }

            if (this.txtInserirMarcaa.getText().length() <= 2) {
                JOptionPane.showMessageDialog(null, "O campo Marca deve ter no mínimo 3 caracteres.");
            } else {
                marca = this.txtInserirMarcaa.getText();
            }

            if (this.txtFormatCusto.getText().length() <= 0) {
                JOptionPane.showMessageDialog(null, "O campo Custo deve ter pelo menos 1 caracterer!");
            } else {
                textoPreco = this.txtFormatCusto.getText();
                textoPreco = textoPreco.replace(",", ".");
                preco = Double.parseDouble(textoPreco); // transformando um dado do tipo String em double.
            }

            Ferramenta f = new Ferramenta(); //instancia produto
            FerramentaDAO dao = new FerramentaDAO(); //conecta sql

            //atualiza os valores
            f.setNome(nome);
            f.setMarca(marca);
            if (preco <= 0.0) {
                JOptionPane.showMessageDialog(null, "O valor não pode ser 0");
            } else {
                f.setCusto(preco);
            }

            if (dao.create(f)) {
//                JOptionPane.showMessageDialog(null, "Ferramenta cadastrada!");

                // limpa campos da interface
                this.txtInserirNome.setText("");
                this.txtInserirMarcaa.setText("");
                this.txtFormatCusto.setText("");

                //atualizando tabela
                readJtable();
            } else {
                this.setVisible(false);
            }
        } catch (Exception ex) {
            System.out.println("erro ao cadastrar ferramenta " + ex);
        }
    }//GEN-LAST:event_btnCadastrarFerramentaActionPerformed

   // BOTAO EXCLUIR
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        this.dispose();
//        if (jTableCadastroFerramenta.getSelectedRow() != -1) {
//            int[] selectedRows = jTableCadastroFerramenta.getSelectedRows();
//            FerramentaDAO dao = new FerramentaDAO();
//
//            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
//            if (resposta == JOptionPane.YES_OPTION) {
//                for (int i = 0; i < selectedRows.length; i++) {
//                    int modelIndex = jTableCadastroFerramenta.convertRowIndexToModel(selectedRows[i]);
//                    int id = (int) jTableCadastroFerramenta.getModel().getValueAt(modelIndex, 0);
//                    Ferramenta f = new Ferramenta();
//                    f.setId(id);
//                    dao.delete(f);
//                }
//
//                // Limpar campos
//                this.txtInserirMarcaa.setText("");
//                this.txtInserirNome.setText("");
//                this.txtFormatCusto.setText("");
//
//                // Atualizar tabela
//                readJtable();
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Selecione um ou mais produtos para excluir.");
//        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtInserirMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirMarcaActionPerformed
        // label do botao marca
    }//GEN-LAST:event_txtInserirMarcaActionPerformed

    private void txtInserirMarcaaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirMarcaaKeyPressed
        // ir pro próximo campo clicando Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            //vai pro inserir marca
            txtFormatCusto.requestFocus();
        }
    }//GEN-LAST:event_txtInserirMarcaaKeyPressed

    private void txtInserirMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirMarcaKeyPressed
        // ir pro próximo campo clicando Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            //vai pro inserir custo
            txtFormatCusto.requestFocus();
        }
    }//GEN-LAST:event_txtInserirMarcaKeyPressed

    private void btnCadastrarFerramentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCadastrarFerramentaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dados();
        }
    }//GEN-LAST:event_btnCadastrarFerramentaKeyPressed

    //pro "0,00" que tava no campo sumir quando o usuario clicar
    private void txtFormatCustoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormatCustoFocusGained

        if ("0,00".equals(txtFormatCusto.getText())) {
            txtFormatCusto.setText("");
        }
    }//GEN-LAST:event_txtFormatCustoFocusGained

    private void txtFormatCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormatCustoKeyPressed
        // ir pro próximo campo clincando Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            btnCadastrarFerramenta.requestFocus();
        }
    }//GEN-LAST:event_txtFormatCustoKeyPressed

    //pro "0" que tava no campo aparecer quando o usuario desclicar
    private void txtFormatCustoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormatCustoFocusLost

//        if ("".equals(txtFormatCusto.getText())) {
//            txtFormatCusto.setValue(0.00);
//        }
    }//GEN-LAST:event_txtFormatCustoFocusLost

    //pro "0,00" que tava no campo sumir quando o usuario clicar
    //pro "0,00" que tava no campo aparecer quando o usuario desclicar
    private void jTableCadastroFerramentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadastroFerramentaMouseClicked
        // TODO add your handling code here:
        if (this.jTableCadastroFerramenta.getSelectedRow() != -1) {

            String nome = this.jTableCadastroFerramenta.getValueAt(this.jTableCadastroFerramenta.getSelectedRow(), 1).toString();
            String marca = this.jTableCadastroFerramenta.getValueAt(this.jTableCadastroFerramenta.getSelectedRow(), 2).toString();
            String aquisicao = this.jTableCadastroFerramenta.getValueAt(this.jTableCadastroFerramenta.getSelectedRow(), 3).toString();

            String aquisicaoModificada = aquisicao.replace("R$ ", "");
            this.txtInserirNome.setText(nome);
            this.txtInserirMarcaa.setText(marca);
            this.txtFormatCusto.setText(aquisicaoModificada);
        }
    }//GEN-LAST:event_jTableCadastroFerramentaMouseClicked

    private void txtInserirNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirNomeActionPerformed

    private void btnCadastrarFerramentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarFerramentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarFerramentaMouseClicked

    private void btnCadastrarFerramentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCadastrarFerramentaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarFerramentaFocusGained

    private void txtInserirNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            //vai pro inserir custo
            txtInserirMarcaa.requestFocus();
        }
    }//GEN-LAST:event_txtInserirNomeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFerramenta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastroFerramenta;
    private javax.swing.JLabel lblFerramenta;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JFormattedTextField txtFormatCusto;
    private javax.swing.JTextField txtInserirMarca;
    private javax.swing.JTextField txtInserirMarcaa;
    private javax.swing.JTextField txtInserirNome;
    // End of variables declaration//GEN-END:variables
}
