package visao;

import dao.AmigoDAO;
import dao.FerramentaDAO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Amigo;
import modelo.Ferramenta;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author josue
 */
public class CadastroAmigo extends javax.swing.JFrame {

    public CadastroAmigo() {

        initComponents();

        //pra centraliazr a exibição dos valores na tabela
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        // Permitir seleção de múltiplas linhas
        jTableCadastroAmigos.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        // Aplicar o renderer às colunas desejadas (ID e Quantidade)
        jTableCadastroAmigos.getColumnModel().getColumn(0).setCellRenderer(centerRenderer); // Coluna ID
        jTableCadastroAmigos.getColumnModel().getColumn(2).setCellRenderer(centerRenderer); // Coluna Telefone

        readJtable(); //carrega a tabela
    }

    public void readJtable() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTableCadastroAmigos.getModel();
        modelo.setNumRows(0); //posiciona na primeira linha da tabela

        AmigoDAO adao = new AmigoDAO();

        for (Amigo a : adao.read()) {

            modelo.addRow(new Object[]{
                a.getIdAmigo(),
                a.getNome(),
                a.getTelefone()
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroAmigos = new javax.swing.JTable();
        txtNome = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnAdicionarAmigo = new javax.swing.JButton();
        btnExcluirAmigo = new javax.swing.JButton();
        jFormatTelefone = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar amigos");

        jTableCadastroAmigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCadastroAmigos.setShowHorizontalLines(true);
        jTableCadastroAmigos.setShowVerticalLines(true);
        jTableCadastroAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadastroAmigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadastroAmigos);
        if (jTableCadastroAmigos.getColumnModel().getColumnCount() > 0) {
            jTableCadastroAmigos.getColumnModel().getColumn(0).setMaxWidth(55);
        }

        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefone.setText("Telefone");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setText("Nome");

        btnAdicionarAmigo.setBackground(new java.awt.Color(64, 61, 57));
        btnAdicionarAmigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionarAmigo.setForeground(new java.awt.Color(22, 219, 101));
        btnAdicionarAmigo.setText("Cadastrar");
        btnAdicionarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAmigoActionPerformed(evt);
            }
        });
        btnAdicionarAmigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarAmigoKeyPressed(evt);
            }
        });

        btnExcluirAmigo.setBackground(new java.awt.Color(64, 61, 57));
        btnExcluirAmigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluirAmigo.setForeground(new java.awt.Color(195, 47, 39));
        btnExcluirAmigo.setText("Cancelar");
        btnExcluirAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAmigoActionPerformed(evt);
            }
        });

        try {
            jFormatTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormatTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFormatTelefoneKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Amigos");

        jButton1.setBackground(new java.awt.Color(195, 47, 39));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblTelefone)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(jFormatTelefone, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluirAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionarAmigo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormatTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluirAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dados() {

        Amigo amg = new Amigo(); //instancia produto
        AmigoDAO dao = new AmigoDAO(); //conecta sql

        //atualiza os valores
        amg.setNome(txtNome.getText());
        amg.setTelefone(jFormatTelefone.getText());

        //insere novo objeto dentro da tabela
        dao.create(amg);

        //limpando os campos
        txtNome.setText("");
        jFormatTelefone.setText("");

        //atualizando tabela
        readJtable();
    }
    private void btnAdicionarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAmigoActionPerformed

        Amigo amg = new Amigo(); //instancia produto
        AmigoDAO dao = new AmigoDAO(); //conecta sql

        //atualiza os valores
        amg.setNome(txtNome.getText());
        amg.setTelefone(jFormatTelefone.getText());

        dao.create(amg);

        //limpando os campos
        txtNome.setText("");
        jFormatTelefone.setText("");

        //atualizando tabela
        readJtable();
    }//GEN-LAST:event_btnAdicionarAmigoActionPerformed

    private void btnAdicionarAmigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarAmigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dados();
        }
    }//GEN-LAST:event_btnAdicionarAmigoKeyPressed

    private void btnExcluirAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAmigoActionPerformed

        this.dispose();
//        if (jTableCadastroAmigos.getSelectedRow() != -1) {
//            int[] selectedRows = jTableCadastroAmigos.getSelectedRows();
//            AmigoDAO dao = new AmigoDAO();
//            
//            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir?", "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
//            
//            if(resposta == JOptionPane.YES_OPTION) {
//                for (int i = 0; i < selectedRows.length; i++) {
//                    int modelIndex = jTableCadastroAmigos.convertRowIndexToModel(selectedRows[i]);
//                    int id = (int) jTableCadastroAmigos.getModel().getValueAt(modelIndex, 0);
//                    Amigo amg = new Amigo();
//                    amg.setIdAmigo(id);
//                    dao.delete(amg);
//
//                    //limpa os campos
//                    txtNome.setText("");
//                    jFormatTelefone.setText("");
//
//                    //atualizando tabela
//                    readJtable();
//                }
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
//        }
    }//GEN-LAST:event_btnExcluirAmigoActionPerformed

    //preencher os campos ao selecionar objeto na tabela
    private void jTableCadastroAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadastroAmigosMouseClicked
        // TODO add your handling code here:
        if (this.jTableCadastroAmigos.getSelectedRow() != -1) {

            String nome = this.jTableCadastroAmigos.getValueAt(this.jTableCadastroAmigos.getSelectedRow(), 1).toString();
            String telefone = this.jTableCadastroAmigos.getValueAt(this.jTableCadastroAmigos.getSelectedRow(), 2).toString();

            this.txtNome.setText(nome);
            this.jFormatTelefone.setText(telefone);

        }
    }//GEN-LAST:event_jTableCadastroAmigosMouseClicked

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // ir pro próximo campo clicando Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            //vai pro inserir custo
            jFormatTelefone.requestFocus();
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void jFormatTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormatTelefoneKeyPressed
        // ir pro próximo campo clicando Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            //vai pro botão Adicionar
            btnAdicionarAmigo.requestFocus();
        }

    }//GEN-LAST:event_jFormatTelefoneKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAmigo;
    private javax.swing.JButton btnExcluirAmigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormatTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastroAmigos;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
