/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.AmigosDAO;
import dao.EmprestimosDAO;
import dao.FerramentaDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import modelo.Amigo;
import modelo.Emprestimos;
import modelo.Ferramenta;

/**
 *
 * @author kauem
 */
public class RealizarEmprestimo extends javax.swing.JFrame {

    private List<Integer> listaIds = new ArrayList<>();

    public RealizarEmprestimo() {

        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTableEmprestimos.getModel();
        jTableEmprestimos.setRowSorter(new TableRowSorter(modelo));

        // Permitir seleção de múltiplas linhas
        jTableEmprestimos.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        //pra centraliazr a exibição dos valores na tabela
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        // Aplicar o renderer às colunas desejadas (ID e Quantidade)
        jTableEmprestimos.getColumnModel().getColumn(2).setCellRenderer(centerRenderer); // Coluna emprestimo

        LocalDate data = LocalDate.now();

        carregarAmigos();
        carregarFerramenta();
        //carregarFerramentas();
        readJtable();
        //readJTableFerr();

    }

    /*puxando ferramentas do bd
    private void carregarFerramentas() {
        FerramentaDAO ferramentaDAO = new FerramentaDAO();
        List<Ferramenta> ferramentas = ferramentaDAO.read();

        readJTableFerr();
    }*/

    /*public void readJTableFerr() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTableFerramentas.getModel();
        modelo.setNumRows(0);

        FerramentaDAO fdao = new FerramentaDAO();

        for (Ferramenta f : fdao.read()) {

            modelo.addRow(new Object[]{
                f.getNome(),
                f.getMarca(),});
        }
    }*/

    //puxando ferramentas do bd
    private void carregarFerramenta() {
        FerramentaDAO ferramentaDAO = new FerramentaDAO();
        List<Ferramenta> ferramentas = ferramentaDAO.read();

        for (Ferramenta ferramenta : ferramentas) {
            jComboBoxFerramenta.addItem(ferramenta.getNome());
        }
    }

    private void carregarAmigos() {
        AmigosDAO amigosDAO = new AmigosDAO();
        List<Amigo> amigos = amigosDAO.read();

        for (Amigo amigo : amigos) {
            jComboBoxAmiguitos.addItem(amigo.getNome());
        }
    }

    public void readJtable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableEmprestimos.getModel();
        modelo.setNumRows(0);
        listaIds.clear();

        EmprestimosDAO edao = new EmprestimosDAO();

        for (Emprestimos e : edao.read()) {

            listaIds.add(e.getID());

            modelo.addRow(new Object[]{
                //e.getID(),
                e.getAmigoEsc(),
                e.getFerramentaEsc(),
                e.getData(),
                e.getStatus()

            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFerramenta = new javax.swing.JLabel();
        lblAmigo = new javax.swing.JLabel();
        btnRealizarEmp = new javax.swing.JButton();
        jComboBoxAmiguitos = new javax.swing.JComboBox<>();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmprestimos = new javax.swing.JTable();
        jComboBoxFerramenta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realizar empréstimo");

        lblFerramenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFerramenta.setText("Ferramenta:");

        lblAmigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAmigo.setText("Amigo:");

        btnRealizarEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRealizarEmp.setText("Realizar Empréstimo");
        btnRealizarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarEmpActionPerformed(evt);
            }
        });

        jComboBoxAmiguitos.setToolTipText("");
        jComboBoxAmiguitos.setName(""); // NOI18N
        jComboBoxAmiguitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAmiguitosActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jTableEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Ferramenta", "Data", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTableEmprestimos);

        jComboBoxFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFerramentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRealizarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmigo)
                            .addComponent(jComboBoxAmiguitos, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAmiguitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRealizarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btnRealizarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarEmpActionPerformed
        // TODO add your handling code here:

        //if (jTableFerramentas.getSelectedRow() != -1) {

            Emprestimos e = new Emprestimos(); //instancia produto
            EmprestimosDAO dao = new EmprestimosDAO(); //conecta sql

            //atualiza os valores
            //e.setFerramentaEsc((String) jTableFerramentas.getValueAt(jTableFerramentas.getSelectedRow(), 0)); //pega id na tabela 0
            e.setFerramentaEsc((String) jComboBoxFerramenta.getSelectedItem());
            e.setAmigoEsc((String) jComboBoxAmiguitos.getSelectedItem());

            try {
                dao.create(e);
            } catch (ParseException ex) {
                Logger.getLogger(RealizarEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
            }

            //atualizando tabela
            readJtable();
        //}
    }//GEN-LAST:event_btnRealizarEmpActionPerformed

    private void jComboBoxAmiguitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAmiguitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAmiguitosActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int[] selectedRows = jTableEmprestimos.getSelectedRows();
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Selecione ao menos uma linha para excluir.");
            return;
        }

        EmprestimosDAO dao = new EmprestimosDAO();

        for (int i = 0; i < selectedRows.length; i++) {
            int modelRow = jTableEmprestimos.convertRowIndexToModel(selectedRows[i]);

            if (modelRow >= 0 && modelRow < listaIds.size()) {
                int id = listaIds.get(modelRow);

                Emprestimos e = new Emprestimos();
                e.setID(id);
                dao.delete(e);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir. Índice inválido.");
                return;
            }
        }

        //atualizando tabela
        readJtable();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jComboBoxFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFerramentaActionPerformed

    }//GEN-LAST:event_jComboBoxFerramentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealizarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnRealizarEmp;
    private javax.swing.JComboBox<String> jComboBoxAmiguitos;
    private javax.swing.JComboBox<String> jComboBoxFerramenta;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmprestimos;
    private javax.swing.JLabel lblAmigo;
    private javax.swing.JLabel lblFerramenta;
    // End of variables declaration//GEN-END:variables
}
