/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view2;

import dao.FerramentaDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Ferramenta;

/**
 *
 * @author kauem
 */
public class jFrmCadastroFerramentas extends javax.swing.JFrame {

    /**
     * Creates new form jFrmCadastroFerramentas
     */
    public jFrmCadastroFerramentas() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroFerramenta.getModel();
        jTableCadastroFerramenta.setRowSorter(new TableRowSorter(modelo));

        readJtable();
    }

    public void readJtable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroFerramenta.getModel();

        FerramentaDAO fdao = new FerramentaDAO();

        for (Ferramenta f : fdao.read()) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getMarca(),
                f.getUnidade(),
                f.getAluguel()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFerramenta = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        txtInserirFerramenta = new javax.swing.JTextField();
        txtInserirMarca = new javax.swing.JTextField();
        txtInserirUnidade = new javax.swing.JTextField();
        btnAdicionarFerramenta = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterarFerramenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroFerramenta = new javax.swing.JTable();
        txtInserirAluguel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar ferramentas");

        lblFerramenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFerramenta.setText("Ferramenta:");

        lblUnidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnidade.setText("Unidade:");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");

        txtInserirFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirFerramentaActionPerformed(evt);
            }
        });

        txtInserirMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirMarcaActionPerformed(evt);
            }
        });

        txtInserirUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirUnidadeActionPerformed(evt);
            }
        });

        btnAdicionarFerramenta.setText("Adicionar");
        btnAdicionarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarFerramentaActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterarFerramenta.setText("Alterar");
        btnAlterarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFerramentaActionPerformed(evt);
            }
        });

        jTableCadastroFerramenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Ferramenta", "Marca", "Valor", "Qtd"
            }
        ));
        jScrollPane1.setViewportView(jTableCadastroFerramenta);

        txtInserirAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirAluguelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Aluguel:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(txtInserirFerramenta))
                                    .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInserirMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInserirUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(txtInserirAluguel)
                                    .addComponent(jLabel2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btnAdicionarFerramenta)
                                .addGap(73, 73, 73)
                                .addComponent(btnExcluir)))
                        .addGap(80, 80, 80)
                        .addComponent(btnAlterarFerramenta)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInserirFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInserirUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInserirMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInserirAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarFerramenta)
                    .addComponent(btnAlterarFerramenta)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtInserirFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirFerramentaActionPerformed

    private void btnAdicionarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFerramentaActionPerformed
        // BOTAO ADICIONAR
        Ferramenta f = new Ferramenta(); //instancia produto
        FerramentaDAO dao = new FerramentaDAO(); //conecta sql

        //atualiza os valores
        f.setNome(txtInserirFerramenta.getText());
        f.setMarca(txtInserirMarca.getText());
        f.setUnidade(Double.parseDouble(txtInserirUnidade.getText()));
        f.setAluguel(Double.parseDouble(txtInserirAluguel.getText()));
        dao.create(f);

        //limpando os campos
        txtInserirFerramenta.setText("");
        txtInserirMarca.setText("");
        txtInserirUnidade.setText("");
        txtInserirAluguel.setText("");

        readJtable();
    }//GEN-LAST:event_btnAdicionarFerramentaActionPerformed

    private void btnAlterarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFerramentaActionPerformed
        // BOTAO ALTERAR

        if (jTableCadastroFerramenta.getSelectedRow() != -1) {

            Ferramenta f = new Ferramenta(); //instancia produto
            FerramentaDAO dao = new FerramentaDAO(); //conecta sql

            //atualiza os valores
            f.setNome(txtInserirFerramenta.getText());
            f.setMarca(txtInserirMarca.getText());
            f.setUnidade(Double.parseDouble(txtInserirUnidade.getText()));
            f.setAluguel(Double.parseDouble(txtInserirAluguel.getText()));
            dao.update(f);

            //limpando os campos
            txtInserirFerramenta.setText("");
            txtInserirMarca.setText("");
            txtInserirUnidade.setText("");
            txtInserirAluguel.setText("");

            readJtable();
        }
    }//GEN-LAST:event_btnAlterarFerramentaActionPerformed

    private void txtInserirAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirAluguelActionPerformed

    private void txtInserirUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirUnidadeActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // BOTAO EXCLUIR
        if (jTableCadastroFerramenta.getSelectedRow() != -1) {

            Ferramenta f = new Ferramenta();
            FerramentaDAO dao = new FerramentaDAO();

            f.setId((int) jTableCadastroFerramenta.getValueAt(jTableCadastroFerramenta.getSelectedRow(), 0));

            dao.delete(f);

            txtInserirFerramenta.setText("");
            txtInserirMarca.setText("");
            txtInserirUnidade.setText("");
            txtInserirAluguel.setText("");

            readJtable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtInserirMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmCadastroFerramentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarFerramenta;
    private javax.swing.JButton btnAlterarFerramenta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastroFerramenta;
    private javax.swing.JLabel lblFerramenta;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JTextField txtInserirAluguel;
    private javax.swing.JTextField txtInserirFerramenta;
    private javax.swing.JTextField txtInserirMarca;
    private javax.swing.JTextField txtInserirUnidade;
    // End of variables declaration//GEN-END:variables
}
