package view2;

import dao.FerramentaDAO;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import model.Ferramenta;

/**
 *
 * @author kauem
 */
public class jFrmCadastroFerramentas extends javax.swing.JFrame {

    private Ferramenta objetoFerramenta;
    /**
     * Creates new form jFrmCadastroFerramentas
     */
    MaskFormatter mfCusto;

    public jFrmCadastroFerramentas() {

        try {
            mfCusto = new MaskFormatter("R$##,##");
        } catch (ParseException ex) {
            System.out.println("erro na criação da mascara");
        }

        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroFerramenta.getModel();
        jTableCadastroFerramenta.setRowSorter(new TableRowSorter(modelo));

        // Permitir seleção de múltiplas linhas
        jTableCadastroFerramenta.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        //pra centraliazr a exibição dos valores na tabela
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);

        // Aplicar o renderer às colunas desejadas (ID e Quantidade)
        jTableCadastroFerramenta.getColumnModel().getColumn(0).setCellRenderer(centerRenderer); // Coluna ID

        readJtable();
    }

    //Método que atualiza a tabela com os valores adicionados
    public void readJtable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroFerramenta.getModel();
        modelo.setNumRows(0);

        FerramentaDAO fdao = new FerramentaDAO();

        for (Ferramenta f : fdao.read()) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getMarca(),
                // f.getCusto(),
                String.format("R$ %.2f", f.getCusto()),
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInserirMarca = new javax.swing.JTextField();
        lblFerramenta = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        txtInserirMarcaa = new javax.swing.JTextField();
        btnAdicionarFerramenta = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterarFerramenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroFerramenta = new javax.swing.JTable();
        txtFormatCusto = new javax.swing.JFormattedTextField(mfCusto);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInserirNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        lblUnidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnidade.setText("Custo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Custo");

        txtInserirMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirMarcaActionPerformed(evt);
            }
        });
        txtInserirMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirMarcaKeyPressed(evt);
            }
        });

        lblFerramenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFerramenta.setText("Ferramenta:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar ferramentas");
        setBackground(new java.awt.Color(239, 35, 60));

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");

        txtInserirMarcaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirMarcaaActionPerformed(evt);
            }
        });
        txtInserirMarcaa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirMarcaaKeyPressed(evt);
            }
        });

        btnAdicionarFerramenta.setBackground(new java.awt.Color(64, 61, 57));
        btnAdicionarFerramenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionarFerramenta.setForeground(new java.awt.Color(22, 219, 101));
        btnAdicionarFerramenta.setText("Cadastrar");
        btnAdicionarFerramenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnAdicionarFerramenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAdicionarFerramentaFocusGained(evt);
            }
        });
        btnAdicionarFerramenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdicionarFerramentaMouseClicked(evt);
            }
        });
        btnAdicionarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarFerramentaActionPerformed(evt);
            }
        });
        btnAdicionarFerramenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarFerramentaKeyPressed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(64, 61, 57));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(195, 47, 39));
        btnExcluir.setText("Deletar");
        btnExcluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterarFerramenta.setBackground(new java.awt.Color(64, 61, 57));
        btnAlterarFerramenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAlterarFerramenta.setForeground(new java.awt.Color(246, 170, 28));
        btnAlterarFerramenta.setText("Editar");
        btnAlterarFerramenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        btnAlterarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFerramentaActionPerformed(evt);
            }
        });

        jTableCadastroFerramenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Ferramenta", "Marca", "Custo de Aquisição"
            }
        ));
        jTableCadastroFerramenta.setShowHorizontalLines(true);
        jTableCadastroFerramenta.setShowVerticalLines(true);
        jTableCadastroFerramenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCadastroFerramentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCadastroFerramenta);

        txtFormatCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtFormatCusto.setValue(0.00);
        txtFormatCusto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFormatCustoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFormatCustoFocusLost(evt);
            }
        });
        txtFormatCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFormatCustoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText(" ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nome:");

        txtInserirNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirNomeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Custo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtFormatCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAdicionarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtInserirMarcaa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAlterarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtInserirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca)
                            .addComponent(txtInserirMarcaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFormatCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdicionarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* dados() => mesmo método do botão adicionar, mas usado pra executar
        a ação do botão ao pressionar enter
     */
    private void dados() {

        Ferramenta f = new Ferramenta(); //instancia produto
        FerramentaDAO dao = new FerramentaDAO(); //conecta sql

        //atualiza os valores
        f.setNome(txtInserirNome.getText());
        f.setMarca(txtInserirMarcaa.getText());
        f.setCusto(Double.parseDouble(txtFormatCusto.getText().replace(',', '.')));

        //insere novo objeto dentro da tabela
        dao.create(f);

        //limpando os campos
        txtInserirNome.setText("");
        txtInserirMarcaa.setText("");
        txtFormatCusto.setText("");

        //atualizando tabela
        readJtable();
    }

    private void txtInserirMarcaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirMarcaaActionPerformed
        //label do botão ferramenta
    }//GEN-LAST:event_txtInserirMarcaaActionPerformed

    // BOTAO ADICIONAR
    private void btnAdicionarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFerramentaActionPerformed
        String nome = "";
        String marca = "";
        double preco = 0.0;
        String textoPreco = "";

        try {
            if (this.txtInserirNome.getText().length() <= 2) {
                JOptionPane.showMessageDialog(null, "O campo Nome deve ter no mínimo 3 caracteres.");
            } else {
                nome = this.txtInserirNome.getText();
            }

            if (this.txtInserirMarcaa.getText().length() <= 2) {
                JOptionPane.showMessageDialog(null, "O campo Marca deve ter no mínimo 3 caracteres.");
            } else {
                marca = this.txtInserirMarcaa.getText();
            }
            
            if (this.txtFormatCusto.getText().length() <= 0) {
                JOptionPane.showMessageDialog(null, "O campo Custo deve ter pelo menos 1 caracterer!");
            } else {
                textoPreco = this.txtFormatCusto.getText();
                textoPreco = textoPreco.replace(",", ".");
                preco = Double.parseDouble(textoPreco); // transformando um dado do tipo String em double.
            }

            Ferramenta f = new Ferramenta(); //instancia produto
            FerramentaDAO dao = new FerramentaDAO(); //conecta sql

            //atualiza os valores
            f.setNome(nome);
            f.setMarca(marca);
            if (preco <= 0.0) {
                JOptionPane.showMessageDialog(null, "O valor não pode ser 0");
            } else {
                f.setCusto(preco);
            }

            if (dao.create(f)) {
//                JOptionPane.showMessageDialog(null, "Ferramenta cadastrada!");

                // limpa campos da interface
                this.txtInserirNome.setText("");
                this.txtInserirMarcaa.setText("");
                this.txtFormatCusto.setText("");

                //atualizando tabela
                readJtable();
            } else {
                this.setVisible(false);
            }
        } catch (Exception ex) {
            System.out.println("erro ao cadastrar ferramenta " + ex);
        }
    }//GEN-LAST:event_btnAdicionarFerramentaActionPerformed

    // BOTAO ALTERAR
    private void btnAlterarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFerramentaActionPerformed

        int id = 0;
        String nome = "";
        String marca = "";
        double preco = 0.0;

        if (this.txtInserirNome.getText().length() <= 2) {
            JOptionPane.showMessageDialog(null, "O campo nome deve ter pelo menos 3 caracteres!");
        } else {
            nome = this.txtInserirNome.getText();
        }

        if (this.txtInserirMarcaa.getText().length() <= 2) {
            JOptionPane.showMessageDialog(null, "O campo marca deve ter pelo menos 3 caracteres!");
        } else {
            marca = this.txtInserirMarcaa.getText();
        }

        if (this.txtFormatCusto.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo marca deve ter pelo menos 1 caracterer!");
        }

        String textoPreco = this.txtFormatCusto.getText();
        textoPreco = textoPreco.replace("R$ ", " ");
        textoPreco = textoPreco.replace(",", ".");
        preco = Double.parseDouble(textoPreco); // transformando um dado do tipo String em double.

        if (this.jTableCadastroFerramenta.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma Ferramenta para Alterar");
        } else {
            id = Integer.parseInt(this.jTableCadastroFerramenta.getValueAt(this.jTableCadastroFerramenta.getSelectedRow(), 0).toString());
        }

        if (jTableCadastroFerramenta.getSelectedRow() != -1) {

            Ferramenta f = new Ferramenta(); //instancia ferramenta
            FerramentaDAO dao = new FerramentaDAO(); //conecta sql

            //atualiza os valores
            f.setNome(nome);
            f.setMarca(marca);
            f.setCusto(preco);
            f.setId(id);

            //update nos dados
            dao.update(f);

            //limpando os campos
            this.txtInserirMarcaa.setText("");
            this.txtInserirNome.setText("");
            this.txtFormatCusto.setText("");

            //atualizando tabela
            readJtable();
        }
    }//GEN-LAST:event_btnAlterarFerramentaActionPerformed
    // BOTAO EXCLUIR
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (jTableCadastroFerramenta.getSelectedRow() != -1) {
            int[] selectedRows = jTableCadastroFerramenta.getSelectedRows();
            FerramentaDAO dao = new FerramentaDAO();

            for (int i = 0; i < selectedRows.length; i++) {
                int modelIndex = jTableCadastroFerramenta.convertRowIndexToModel(selectedRows[i]);
                int id = (int) jTableCadastroFerramenta.getModel().getValueAt(modelIndex, 0);
                Ferramenta f = new Ferramenta();
                f.setId(id);
                dao.delete(f);
            }

            // Limpar campos
            this.txtInserirMarcaa.setText("");
            this.txtInserirNome.setText("");
            this.txtFormatCusto.setText("");

            // Atualizar tabela
            readJtable();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um ou mais produtos para excluir.");
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtInserirMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirMarcaActionPerformed
        // label do botao marca
    }//GEN-LAST:event_txtInserirMarcaActionPerformed

    private void txtInserirMarcaaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirMarcaaKeyPressed
        // ir pro próximo campo clicando Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            //vai pro inserir marca
            txtInserirMarca.requestFocus();
        }
    }//GEN-LAST:event_txtInserirMarcaaKeyPressed

    private void txtInserirMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirMarcaKeyPressed
        // ir pro próximo campo clicando Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            //vai pro inserir custo
            txtFormatCusto.requestFocus();
        }
    }//GEN-LAST:event_txtInserirMarcaKeyPressed

    private void btnAdicionarFerramentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarFerramentaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dados();
        }
    }//GEN-LAST:event_btnAdicionarFerramentaKeyPressed

    //pro "0,00" que tava no campo sumir quando o usuario clicar
    private void txtFormatCustoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormatCustoFocusGained

        if ("0,00".equals(txtFormatCusto.getText())) {
            txtFormatCusto.setText("");
        }
    }//GEN-LAST:event_txtFormatCustoFocusGained

    private void txtFormatCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormatCustoKeyPressed
        // ir pro próximo campo clincando Enter
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }
    }//GEN-LAST:event_txtFormatCustoKeyPressed

    //pro "0" que tava no campo aparecer quando o usuario desclicar
    private void txtFormatCustoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormatCustoFocusLost

//        if ("".equals(txtFormatCusto.getText())) {
//            txtFormatCusto.setValue(0.00);
//        }
    }//GEN-LAST:event_txtFormatCustoFocusLost

    //pro "0,00" que tava no campo sumir quando o usuario clicar
    //pro "0,00" que tava no campo aparecer quando o usuario desclicar
    private void jTableCadastroFerramentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCadastroFerramentaMouseClicked
        // TODO add your handling code here:
        if (this.jTableCadastroFerramenta.getSelectedRow() != -1) {

            String nome = this.jTableCadastroFerramenta.getValueAt(this.jTableCadastroFerramenta.getSelectedRow(), 1).toString();
            String marca = this.jTableCadastroFerramenta.getValueAt(this.jTableCadastroFerramenta.getSelectedRow(), 2).toString();
            String aquisicao = this.jTableCadastroFerramenta.getValueAt(this.jTableCadastroFerramenta.getSelectedRow(), 3).toString();
            
            String aquisicaoModificada = aquisicao.replace("R$ ", "");
            this.txtInserirNome.setText(nome);
            this.txtInserirMarcaa.setText(marca);
            this.txtFormatCusto.setText(aquisicaoModificada);
        }
    }//GEN-LAST:event_jTableCadastroFerramentaMouseClicked

    private void txtInserirNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirNomeActionPerformed

    private void btnAdicionarFerramentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarFerramentaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarFerramentaMouseClicked

    private void btnAdicionarFerramentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAdicionarFerramentaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarFerramentaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmCadastroFerramentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarFerramenta;
    private javax.swing.JButton btnAlterarFerramenta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastroFerramenta;
    private javax.swing.JLabel lblFerramenta;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JFormattedTextField txtFormatCusto;
    private javax.swing.JTextField txtInserirMarca;
    private javax.swing.JTextField txtInserirMarcaa;
    private javax.swing.JTextField txtInserirNome;
    // End of variables declaration//GEN-END:variables
}
