/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view2;

import dao.FerramentaDAO;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.MaskFormatter;
import model.Ferramenta;

/**
 *
 * @author kauem
 */
public class jFrmCadastroFerramentas extends javax.swing.JFrame {

    /**
     * Creates new form jFrmCadastroFerramentas
     */
    MaskFormatter mfCusto;

    public jFrmCadastroFerramentas() {

        try {
            mfCusto = new MaskFormatter("R$##,##");
        } catch (ParseException ex) {
            System.out.println("erro na criação da mascara");
        }

        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroFerramenta.getModel();
        jTableCadastroFerramenta.setRowSorter(new TableRowSorter(modelo));

        readJtable();
    }

    public void readJtable() {
        DefaultTableModel modelo = (DefaultTableModel) jTableCadastroFerramenta.getModel();

        modelo.setNumRows(0);
        FerramentaDAO fdao = new FerramentaDAO();

        for (Ferramenta f : fdao.read()) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getMarca(),
                String.format("R$ %.2f",f.getCusto()  ),
                "R$" + f.getAluguel()
            });

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFerramenta = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        txtInserirFerramenta = new javax.swing.JTextField();
        txtInserirMarca = new javax.swing.JTextField();
        txtInserirUnidade = new javax.swing.JTextField();
        btnAdicionarFerramenta = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterarFerramenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCadastroFerramenta = new javax.swing.JTable();
        txtInserirAluguel = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFormatCusto = new javax.swing.JFormattedTextField(mfCusto);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar ferramentas");

        lblFerramenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFerramenta.setText("Ferramenta:");

        lblUnidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnidade.setText("Custo de aq:");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarca.setText("Marca:");

        txtInserirFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirFerramentaActionPerformed(evt);
            }
        });
        txtInserirFerramenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirFerramentaKeyPressed(evt);
            }
        });

        txtInserirMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirMarcaActionPerformed(evt);
            }
        });
        txtInserirMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirMarcaKeyPressed(evt);
            }
        });

        txtInserirUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirUnidadeActionPerformed(evt);
            }
        });
        txtInserirUnidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirUnidadeKeyPressed(evt);
            }
        });

        btnAdicionarFerramenta.setText("Adicionar");
        btnAdicionarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarFerramentaActionPerformed(evt);
            }
        });
        btnAdicionarFerramenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAdicionarFerramentaKeyPressed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterarFerramenta.setText("Alterar");
        btnAlterarFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFerramentaActionPerformed(evt);
            }
        });

        jTableCadastroFerramenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ferramenta", "Marca", "Custo de Aquisição", "Aluguel", "Qtd"
            }
        ));
        jScrollPane1.setViewportView(jTableCadastroFerramenta);

        txtInserirAluguel.setToolTipText("");
        txtInserirAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInserirAluguelActionPerformed(evt);
            }
        });
        txtInserirAluguel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInserirAluguelKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Aluguel:");

        txtFormatCusto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtFormatCusto.setValue(0.00);
        txtFormatCusto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFormatCustoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFormatCustoFocusLost(evt);
            }
        });
        txtFormatCusto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFormatCustoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                        .addComponent(txtInserirFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                    .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInserirMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtInserirUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(txtInserirAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(btnAdicionarFerramenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluir)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(btnAlterarFerramenta))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFormatCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInserirFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInserirUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFormatCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInserirMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInserirAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarFerramenta)
                    .addComponent(btnAlterarFerramenta)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dados() {
        Ferramenta f = new Ferramenta(); //instancia produto
        FerramentaDAO dao = new FerramentaDAO(); //conecta sql

        //atualiza os valores
        f.setNome(txtInserirFerramenta.getText());
        f.setMarca(txtInserirMarca.getText());
        f.setCusto(Double.parseDouble(txtFormatCusto.getText().replace(',', '.')));
        f.setAluguel(Double.parseDouble(txtInserirAluguel.getText()));
        dao.create(f);

        //limpando os campos
        txtInserirFerramenta.setText("");
        txtInserirMarca.setText("");
        txtFormatCusto.setText("");
        txtInserirAluguel.setText("");

        readJtable();
    }

    private void txtInserirFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirFerramentaActionPerformed

    private void btnAdicionarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFerramentaActionPerformed
        // BOTAO ADICIONAR
        Ferramenta f = new Ferramenta(); //instancia produto
        FerramentaDAO dao = new FerramentaDAO(); //conecta sql

        //atualiza os valores
        f.setNome(txtInserirFerramenta.getText());
        f.setMarca(txtInserirMarca.getText());
        f.setCusto(Double.parseDouble(txtFormatCusto.getText().replace(',', '.')));
        f.setAluguel(Double.parseDouble(txtInserirAluguel.getText()));
        dao.create(f);

        //limpando os campos
        txtInserirFerramenta.setText("");
        txtInserirMarca.setText("");
        txtFormatCusto.setText("");
        txtInserirAluguel.setText("");

        readJtable();
    }//GEN-LAST:event_btnAdicionarFerramentaActionPerformed

    private void btnAlterarFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFerramentaActionPerformed
        // BOTAO ALTERAR

        if (jTableCadastroFerramenta.getSelectedRow() != -1) {

            Ferramenta f = new Ferramenta(); //instancia produto
            FerramentaDAO dao = new FerramentaDAO(); //conecta sql

            //atualiza os valores
            f.setNome(txtInserirFerramenta.getText());
            f.setMarca(txtInserirMarca.getText());
            f.setCusto(Double.parseDouble(txtFormatCusto.getText().replace(',', '.')));
            f.setAluguel(Double.parseDouble(txtInserirAluguel.getText()));
            dao.update(f);

            //limpando os campos
            txtInserirFerramenta.setText("");
            txtInserirMarca.setText("");
            txtFormatCusto.setText("");
            txtInserirAluguel.setText("");

            readJtable();
        }
    }//GEN-LAST:event_btnAlterarFerramentaActionPerformed

    private void txtInserirAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirAluguelActionPerformed

    private void txtInserirUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirUnidadeActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // BOTAO EXCLUIR
        if (jTableCadastroFerramenta.getSelectedRow() != -1) {

            Ferramenta f = new Ferramenta();
            FerramentaDAO dao = new FerramentaDAO();

            f.setId((int) jTableCadastroFerramenta.getValueAt(jTableCadastroFerramenta.getSelectedRow(), 0));

            dao.delete(f);

            txtInserirFerramenta.setText("");
            txtInserirMarca.setText("");
            txtFormatCusto.setText("");
            txtInserirAluguel.setText("");

            readJtable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtInserirMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInserirMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInserirMarcaActionPerformed

    private void txtInserirFerramentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirFerramentaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtInserirMarca.requestFocus();
        }

    }//GEN-LAST:event_txtInserirFerramentaKeyPressed

    private void txtInserirMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirMarcaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtFormatCusto.requestFocus();
        }
    }//GEN-LAST:event_txtInserirMarcaKeyPressed

    private void txtInserirUnidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirUnidadeKeyPressed
        // TODO add your handling code here: (provavelmente vai ser excluido)
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtInserirAluguel.requestFocus();
        }
    }//GEN-LAST:event_txtInserirUnidadeKeyPressed

    private void txtInserirAluguelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInserirAluguelKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAdicionarFerramenta.requestFocus();
        }
    }//GEN-LAST:event_txtInserirAluguelKeyPressed

    private void btnAdicionarFerramentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAdicionarFerramentaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dados();
        }
    }//GEN-LAST:event_btnAdicionarFerramentaKeyPressed

    private void txtFormatCustoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormatCustoFocusGained
        // TODO add your handling code here:
        if ("0,00".equals(txtFormatCusto.getText())) {
            txtFormatCusto.setText("");
        }
    }//GEN-LAST:event_txtFormatCustoFocusGained

    private void txtFormatCustoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFormatCustoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtInserirAluguel.requestFocus();
        }
    }//GEN-LAST:event_txtFormatCustoKeyPressed

    private void txtFormatCustoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFormatCustoFocusLost
        // TODO add your handling code here:
        if ("".equals(txtFormatCusto.getText())) {
                    txtFormatCusto.setValue(0.00);
                }
    }//GEN-LAST:event_txtFormatCustoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrmCadastroFerramentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrmCadastroFerramentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarFerramenta;
    private javax.swing.JButton btnAlterarFerramenta;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCadastroFerramenta;
    private javax.swing.JLabel lblFerramenta;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JFormattedTextField txtFormatCusto;
    private javax.swing.JTextField txtInserirAluguel;
    private javax.swing.JTextField txtInserirFerramenta;
    private javax.swing.JTextField txtInserirMarca;
    private javax.swing.JTextField txtInserirUnidade;
    // End of variables declaration//GEN-END:variables
}
